# Generated by Django 6.0.3 on 2026-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_subject_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
