# Generated by Django 6.0.4 on 2026-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI (Google Pay / PhonePe / Paytm)'), ('card', 'Credit / Debit Card'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free Session')], default='cash', max_length=20),
        ),
    ]
