# Generated by Django 6.0.4 on 2026-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
